// <auto-generated />
namespace UserLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InsertUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202205111816119_InsertUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
